# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # HA 2023.2 -> 3.10
        # HA 2023.3 -> 3.10, 3.11
        # HA 2023.8 -> 3.11
        # HA 2023.11 -> 3.11, 3.12
        # 0.13.17 -> HA 2023.4.0
        # 0.13.107 -> HA 2024.3.0
        include:
          - hass-test-cc-version: "0.13.17"
            python-version: "3.10"
          - hass-test-cc-version: "0.13.17"
            python-version: "3.11"
          - hass-test-cc-version: "0.13.107"
            python-version: "3.11"
          - hass-test-cc-version: "0.13.107"
            python-version: "3.12"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pytest-homeassistant-custom-component==${{ matrix.hass-test-cc-version }}
      - name: Test with pytest
        run: |
          pytest
